FROM node:24-alpine

WORKDIR /workspace

RUN npm install --omit=dev --no-save \
  prisma@7.9.1 \
  typescript@6.0.3 \
  tsx@4.23.12 \
  dotenv@17.4.2

COPY ./prisma.config.ts ./prisma.config.ts
COPY ./prisma ./prisma

ENTRYPOINT ["./node_modules/.bin/prisma", "migrate", "deploy"]