import { CompilerMetadataBridge } from "./src/infrastructure/adapters/inbound/CompilerMetadataBridge.adapter.js";

CompilerMetadataBridge.activate();

export { ValueMetadataDefinition } from "./src/domain/ValueMetadataDefinition.js";
export { ListMetadataDefinition } from "./src/domain/ListMetadataDefinition.js";
export { RecordMetadataDefinition } from "./src/domain/RecordMetadataDefinition.js";
export { MetadataDiscovery } from "./src/domain/MetadataDiscovery.js";
export { MetadataBoundaryError } from "./src/domain/MetadataBoundary.error.js";
export { DESIGN_TYPE_METADATA } from "./src/domain/DesignTypeMetadata.js";
export { DESIGN_PARAMETER_TYPES_METADATA } from "./src/domain/DesignParameterTypesMetadata.js";
export { DESIGN_RETURN_TYPE_METADATA } from "./src/domain/DesignReturnTypeMetadata.js";
export type { IRuntimeType } from "./src/domain/IRuntimeType.js";
export type { ICompilerMetadataDecorator } from "./src/domain/ICompilerMetadataDecorator.js";
export type { ICompilerMetadataRejectionCode } from "./src/domain/ICompilerMetadataRejectionCode.js";
export type { IMetadataBoundaryErrorCode } from "./src/domain/IMetadataBoundaryErrorCode.js";
export type { IClass } from "./src/domain/IClass.js";
export type { IConstructableClass } from "./src/domain/IConstructableClass.js";
export type { IMetadataKind } from "./src/domain/IMetadataKind.js";
export type { IMetadataSide } from "./src/domain/IMetadataSide.js";
export type { IMetadataLookup } from "./src/domain/IMetadataLookup.js";
export type { IMetadataDefinitionIdentity } from "./src/domain/IMetadataDefinitionIdentity.js";
export type { IMethodKey } from "./src/domain/IMethodKey.js";
export type { IMethodParameters } from "./src/domain/IMethodParameters.js";
export type { IStaticMemberKey } from "./src/domain/IStaticMemberKey.js";
export type { IParameterIndex } from "./src/domain/IParameterIndex.js";
export type { IMetadataClassAddress } from "./src/domain/IMetadataClassAddress.js";
export type { IInstanceMemberMetadataAddress } from "./src/domain/IInstanceMemberMetadataAddress.js";
export type { IInstanceMethodParameterMetadataAddress } from "./src/domain/IInstanceMethodParameterMetadataAddress.js";
export type { IInstanceMetadataAddress } from "./src/domain/IInstanceMetadataAddress.js";
export type { IStaticMemberMetadataAddress } from "./src/domain/IStaticMemberMetadataAddress.js";
export type { IStaticMethodParameterMetadataAddress } from "./src/domain/IStaticMethodParameterMetadataAddress.js";
export type { IConstructorParameterMetadataAddress } from "./src/domain/IConstructorParameterMetadataAddress.js";
export type { IClassMetadataAddress } from "./src/domain/IClassMetadataAddress.js";
export type { IMetadataReadAddress } from "./src/domain/IMetadataReadAddress.js";
export type { IDynamicInstanceMetadataAddress } from "./src/domain/IDynamicInstanceMetadataAddress.js";
export type { IDynamicClassMetadataAddress } from "./src/domain/IDynamicClassMetadataAddress.js";
export type { IDiscoveredMetadataAddress } from "./src/domain/IDiscoveredMetadataAddress.js";
export type { IMetadataAddressRejectionCode } from "./src/domain/IMetadataAddressRejectionCode.js";
export type { IMetadataAddressRejection } from "./src/domain/IMetadataAddressRejection.js";
export type { IMetadataWriteResult } from "./src/domain/IMetadataWriteResult.js";
export type { IMetadataRead } from "./src/domain/IMetadataRead.js";
export type { IMetadataPresenceResult } from "./src/domain/IMetadataPresenceResult.js";
export type { IMetadataDeletionResult } from "./src/domain/IMetadataDeletionResult.js";
export type { IMetadataLocationsResult } from "./src/domain/IMetadataLocationsResult.js";
export type { IMetadataDefinitionsResult } from "./src/domain/IMetadataDefinitionsResult.js";
export type { ILegacyMetadataDecorator } from "./src/domain/ILegacyMetadataDecorator.js";
